use_frameworks!

platform :ios, '8.0'

target 'XHMPodLib_Example' do
  pod 'XHMPodLib', :path => '../'

  target 'XHMPodLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
